# Development Scripts

In [1]:
from MuonDataFrame import *
file = "processed_data/events_data_frame_410.h5"
mdfo = MuonDataFrame(file, isNew=False, d1="last") #Muon Data Frame Object 
mdf = mdfo.events_df

In [6]:
from MuDataFrame import *
file1 = "processed_data/run410.csv"
mdfo1 = MuDataFrame(file1) #Muon Data Frame Object 
mdf1 = mdfo1.events_df

In [7]:
mdf1.columns

Index(['event_num', 'event_time', 'deadtime', 'l1hit', 'l2hit', 'l3hit',
       'l4hit', 'r1hit', 'r2hit', 'r3hit', 'r4hit', 'SCh0', 'SCh1', 'SCh2',
       'SCh3', 'SCh4', 'SCh5', 'SCh6', 'SCh7', 'SCh8', 'SCh9', 'SCh10',
       'SCh11', 'L1', 'R1', 'L2', 'R2', 'L3', 'R3', 'L4', 'R4', 'ADC0', 'ADC1',
       'ADC2', 'ADC3', 'ADC4', 'ADC5', 'ADC6', 'ADC7', 'ADC8', 'ADC9', 'ADC10',
       'ADC11', 'TopCounter', 'BottomCounter', 'sumL1', 'sumL2', 'sumL3',
       'sumL4', 'diffL1', 'diffL2', 'diffL3', 'diffL4', 'asymL1', 'asymL2',
       'asymL3', 'asymL4', 'numLHit', 'theta_x1', 'theta_y1', 'theta_x2',
       'theta_y2', 'z_angle', 'SmallCounter', 'Run_Num'],
      dtype='object')

In [8]:
mdfo1.show()

,event_num,event_time,deadtime,l1hit,l2hit,l3hit,l4hit,r1hit,r2hit,r3hit,...,asymL3,asymL4,numLHit,theta_x1,theta_y1,theta_x2,theta_y2,z_angle,SmallCounter,Run_Num
0,0,2021-02-13 17:51:53.043620,0,1,0,1,1,0,0,1,...,-0.175355,0.074766,5,NaN,NaN,-48.858437,-268.760653,NaN,NaN,410
1,1,2021-02-13 17:51:53.553858,0,1,1,1,0,1,1,1,...,0.185185,NaN,6,-107.990952,-121.595608,NaN,NaN,NaN,NaN,410
2,2,2021-02-13 17:51:53.723748,0,1,1,1,1,1,1,1,...,0.000000,-0.005291,8,86.739444,151.387014,-inf,-0.000000,12.929503,NaN,410
3,3,2021-02-13 17:51:54.233733,0,1,1,1,0,1,1,1,...,-0.005181,NaN,6,4.892250,2684.086902,NaN,NaN,NaN,NaN,410
4,4,2021-02-13 17:51:54.544048,0,1,1,1,1,1,1,1,...,0.252525,-0.081340,8,-9.918775,-1323.875753,-36.910544,-355.758108,10.370192,NaN,410
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,2021-02-14 03:02:40.577578,0,1,1,1,1,1,1,1,...,-0.115385,0.114286,8,-42.971835,-305.577491,-113.500211,-115.693401,10.510505,NaN,410
99996,99996,2021-02-14 03:02:40.717577,0,1,1,0,0,1,1,0,...,NaN,NaN,4,22.761054,576.916413,NaN,NaN,NaN,NaN,410
99997,99997,2021-02-14 03:02:40.897585,0,1,1,1,1,1,1,1,...,0.049020,0.042654,8,-1.793661,-7320.905949,99.710949,131.692914,14.279599,NaN,410
99998,99998,2021-02-14 03:02:41.227664,0,1,1,1,1,1,1,1,...,-0.118182,-0.183099,8,-172.631440,-76.065087,177.536218,73.963643,27.007415,NaN,410
99999,99999,2021-02-14 03:02:41.317764,0,1,1,0,0,1,1,1,...,NaN,NaN,6,409.255568,32.085637,NaN,NaN,NaN,NaN,410